Repository Homerun-Ticket/Ticketable-MSA, pull requests merged in 2025-04, with the labels that each got.

#11 ✨ Feat: 대기열 모듈 분리 및 게이트웨이 필터 적용 (1차)
  module-gateway/build.gradle
  module-gateway/src/main/java/com/example/modulegateway/filter/WaitingQueueGatewayFilterFactory.java
  module-gateway/src/main/resources/application-local.yml
  module-ticket/src/main/java/com/example/moduleticket/config/LuaScriptConfig.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/repository/ReservationRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationService.java
  module-waiting/.gitattributes
  module-waiting/.gitignore
  module-waiting/build.gradle
  module-waiting/gradle/wrapper/gradle-wrapper.jar
  module-waiting/gradle/wrapper/gradle-wrapper.properties
  module-waiting/gradlew
  module-waiting/gradlew.bat
  module-waiting/src/main/java/com/example/modulewaiting/ModuleWaitingApplication.java
  module-waiting/src/main/java/com/example/modulewaiting/config/LuaScriptConfig.java
  module-waiting/src/main/java/com/example/modulewaiting/config/ScheduleConfig.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/QueueSystemConstants.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/WaitingQueue.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/WaitingQueueAspect.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/controller/WaitingQueueController.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/dto/WaitingResponse.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/ProceedQueueService.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/QueueManager.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/RedisProceedQueueService.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/RedisProceedQueueServiceV2.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/RedisWaitingQueueService.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/WaitingQueueService.java
  module-waiting/src/main/resources/application.properties
  module-waiting/src/main/resources/lua/moveWaitingToProceed.lua
  module-waiting/src/main/resources/lua/moveWaitingToProceedV2.lua
  module-waiting/src/test/java/com/example/modulewaiting/ModuleWaitingApplicationTests.java
  settings.gradle
Labels: ✨Feat , ♻️Refactor

#14 ✨ Feat & 🐛 Fix: MSA 서버 분리로 인한 쿼리 변경 및 캐시 처리 변경
  module-common/src/test/java/com/example/modulecommon/ModuleCommonApplicationTests.java
  module-game/build.gradle
  module-game/src/main/java/com/example/modulegame/config/CachingConfig.java
  module-game/src/main/java/com/example/modulegame/config/FeignClientsConfig.java
  module-game/src/main/java/com/example/modulegame/config/RedisSubscriberConfig.java
  module-game/src/main/java/com/example/modulegame/domain/game/controller/GameController.java
  module-game/src/main/java/com/example/modulegame/domain/game/event/TicketEvent.java
  module-game/src/main/java/com/example/modulegame/domain/game/event/listener/RedisEventListener.java
  module-game/src/main/java/com/example/modulegame/domain/game/repository/GameRepository.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameCacheService.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameService.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SeatController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SectionController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/StadiumController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/dto/response/SectionCodeMapping.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/dto/response/SectionTypeMapping.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/dto/response/SectionTypeSeatCountResponse.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SeatRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatService.java
  module-game/src/main/java/com/example/modulegame/feign/client/AuctionClient.java
  module-game/src/main/java/com/example/modulegame/feign/client/ReservationClient.java
  module-game/src/main/java/com/example/modulegame/feign/client/TicketClient.java
  module-ticket/src/main/java/com/example/moduleticket/config/RedisConfig.java
  module-ticket/src/main/java/com/example/moduleticket/domain/auction/controller/AuctionController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/auction/service/AuctionService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/controller/ReservationController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/event/TicketEvent.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/event/publisher/TicketPublisher.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/repository/ReservationRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/controller/TicketController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/repository/TicketRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketService.java
Labels: 🐛 Bug, ✨Feat 

#16 ♻️ Refactor : 예매로직 서비스 분리 및 리팩토링
  module-ticket/build.gradle
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/controller/ReservationController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/dto/ReservationDto.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/dto/ReservationResponse.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/entity/Reservation.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/repository/ReservationRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationCreateService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationValidator.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketSeatService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketService.java
Labels: 🐛 Bug, ♻️Refactor

#21 ✨ Feat : 대기열 등록 api 추가
  module-gateway/build.gradle
  module-gateway/src/main/java/com/example/modulegateway/GateWayController.java
  module-gateway/src/main/java/com/example/modulegateway/config/GatewayUriMetricsConfiguration.java
  module-gateway/src/main/java/com/example/modulegateway/config/WebClientConfig.java
  module-gateway/src/main/java/com/example/modulegateway/dto/RouteCreateRequest.java
  module-gateway/src/main/java/com/example/modulegateway/filter/WaitingQueueGatewayFilterFactory.java
  module-gateway/src/main/resources/application-local.yml
  module-waiting/build.gradle
  module-waiting/src/main/resources/application.properties
Labels: ✨Feat 

#23 ✨ Feat : 그라파나 연동 대기열 적용/해제 자동화
  module-gateway/src/main/java/com/example/modulegateway/GateWayController.java
  module-gateway/src/main/java/com/example/modulegateway/GateWayQueueService.java
Labels: ✨Feat 

#24 RateLimiter 기능 추가
  module-auth/build.gradle
  module-auth/src/main/java/com/example/moduleauth/domain/auth/dto/request/LoginRequest.java
  module-auth/src/main/java/com/example/moduleauth/domain/auth/dto/response/RecaptchaResponse.java
  module-auth/src/main/java/com/example/moduleauth/domain/auth/service/AuthService.java
  module-auth/src/main/java/com/example/moduleauth/domain/auth/service/ReCaptchaService.java
  module-auth/src/main/resources/application.properties
  module-auth/src/main/resources/static/login.html
  module-auth/src/test/resources/application-test.properties
  module-common/src/main/java/com/example/modulecommon/exception/ErrorCode.java
  module-gateway/build.gradle
  module-gateway/src/main/java/com/example/modulegateway/config/RateLimiterConfig.java
  module-gateway/src/main/resources/application-local.yml
  module-ticket/build.gradle
  module-ticket/src/main/resources/static/login.html
  module-ticket/src/main/resources/static/point-charge.html
Labels: ✨Feat 
