Repository Homerun-Ticket/Ticketable-MSA, pull requests merged in 2025-05, with the labels that each got.

#25 ✨ Feat : 티켓 환불 로직 추가
  module-game/src/main/java/com/example/modulegame/common/exception/ErrorResponse.java
  module-game/src/main/java/com/example/modulegame/common/exception/GlobalExceptionHandler.java
  module-game/src/main/java/com/example/modulegame/domain/game/dto/SeatDetailDto.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SeatController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SeatRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatService.java
  module-point/build.gradle
  module-point/src/main/java/com/example/modulepoint/config/AsyncConfig.java
  module-point/src/main/java/com/example/modulepoint/config/RedisConfig.java
  module-point/src/main/java/com/example/modulepoint/config/RedisStreamInitializer.java
  module-point/src/main/java/com/example/modulepoint/domain/point/controller/PointController.java
  module-point/src/main/java/com/example/modulepoint/domain/point/dto/RefundDto.java
  module-point/src/main/java/com/example/modulepoint/domain/point/dto/request/PointPaymentRequestDto.java
  module-point/src/main/java/com/example/modulepoint/domain/point/service/RefundStreamConsumer.java
  module-ticket/build.gradle
  module-ticket/src/main/java/com/example/moduleticket/RefundQueueService.java
  module-ticket/src/main/java/com/example/moduleticket/config/OpenFeignConfig.java
  module-ticket/src/main/java/com/example/moduleticket/config/RedisConfig.java
  module-ticket/src/main/java/com/example/moduleticket/config/WebConfig.java
  module-ticket/src/main/java/com/example/moduleticket/domain/auction/service/AuctionService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/controller/ReservationController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/dto/ReservationResponse.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/entity/Reservation.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/entity/ReserveSeat.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationCreateService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationValidator.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/controller/TicketController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/dto/RefundDto.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/dto/TicketContext.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/entity/Ticket.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/entity/TicketPayment.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/event/listener/ReservationUnknownFailureEventListener.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/repository/TicketRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketCreateService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketPriceCalculator.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketSeatService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketService.java
  module-ticket/src/main/java/com/example/moduleticket/feign/FeignClientErrorDecoder.java
  module-ticket/src/main/java/com/example/moduleticket/feign/GameClient.java
  module-ticket/src/main/java/com/example/moduleticket/feign/PaymentClient.java
  module-ticket/src/main/java/com/example/moduleticket/feign/SeatClient.java
  module-ticket/src/main/java/com/example/moduleticket/feign/dto/SeatDetailDto.java
  module-ticket/src/main/java/com/example/moduleticket/feign/dto/request/PaymentRequest.java
  module-ticket/src/main/java/com/example/moduleticket/feign/dto/request/PointPaymentRequestDto.java
  module-ticket/src/main/java/com/example/moduleticket/global/annotation/LoginUser.java
  module-ticket/src/main/java/com/example/moduleticket/global/argumentresolver/AuthUser.java
  module-ticket/src/main/java/com/example/moduleticket/global/argumentresolver/AuthUserArgumentResolver.java
  module-ticket/src/main/java/com/example/moduleticket/global/entity/Timestamped.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/ErrorCode.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/ErrorResponse.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/GlobalExceptionHandler.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/ServerException.java
  module-ticket/src/main/java/com/example/moduleticket/util/SeatHoldRedisUtil.java
Labels: ✨Feat , ♻️Refactor

#27 ✨ Feat : 서버 간 통신 방식 테스트 및 캐시 로직 변경
  build.gradle
  module-game/build.gradle
  module-game/src/main/java/com/example/modulegame/config/GrpcClientConfig.java
  module-game/src/main/java/com/example/modulegame/config/RSocketClientConfig.java
  module-game/src/main/java/com/example/modulegame/domain/game/event/listener/RedisEventListener.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameCacheService.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameGrpcClientService.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameRSocketClientService.java
  module-game/src/main/java/com/example/modulegame/domain/game/util/GameCacheHelper.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SectionController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SeatRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatService.java
  module-game/src/main/proto/ticket.proto
  module-game/src/main/resources/application.properties
  module-gateway/src/main/resources/application-local.yml
  module-ticket/build.gradle
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/controller/ReservationController.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/repository/ReservationRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketGrpcService.java
  module-ticket/src/main/java/com/example/moduleticket/grpc/GrpcServerRunner.java
  module-ticket/src/main/proto/ticket.proto
  module-ticket/src/main/resources/application.properties
Labels: ✨Feat 

#29 Feat/auction 경매 기능 중 포인트 관련 로직 수정
  module-auction/src/main/java/com/example/moduleauction/config/RedisConfig.java
  module-auction/src/main/java/com/example/moduleauction/config/WebConfig.java
  module-auction/src/main/java/com/example/moduleauction/config/annotation/LoginUser.java
  module-auction/src/main/java/com/example/moduleauction/config/argumentresolver/AuthUserArgumentResolver.java
  module-auction/src/main/java/com/example/moduleauction/config/exception/ErrorCode.java
  module-auction/src/main/java/com/example/moduleauction/config/exception/ErrorResponse.java
  module-auction/src/main/java/com/example/moduleauction/config/exception/GlobalExceptionHandler.java
  module-auction/src/main/java/com/example/moduleauction/config/exception/ServerException.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/controller/AuctionController.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/dto/AuctionDetailDto.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/dto/RecoveryDto.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/dto/RefundDto.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/dto/TicketChangeOwnerDto.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/dto/response/AuctionResponse.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/entity/Auction.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/entity/AuctionHistory.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/entity/AuctionTicketInfo.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/entity/AuthUser.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/entity/Timestamped.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/repository/AuctionRepository.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/repository/AuctionRepositoryQuery.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionHistoryService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionPaymentService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionTicketInfoService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/PointQueueService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/TicketQueueService.java
  module-auction/src/main/java/com/example/moduleauction/feign/PaymentClient.java
  module-auction/src/main/java/com/example/moduleauction/feign/dto/PaymentDto.java
  module-auction/src/main/java/com/example/moduleauction/feign/dto/request/PointPaymentRequestDto.java
  module-auction/src/main/java/com/example/moduleauction/util/AuctionBidRedisUtil.java
  module-auction/src/main/java/com/example/moduleauction/util/PageUtil.java
  module-point/src/main/java/com/example/modulepoint/domain/point/dto/RecoveryDto.java
  module-point/src/main/java/com/example/modulepoint/domain/point/enums/PointHistoryType.java
  module-point/src/main/java/com/example/modulepoint/domain/point/service/RecoveryStreamConsumer.java
  module-ticket/src/main/java/com/example/moduleticket/config/RedisStreamConfig.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/dto/TicketChangeOwnerDto.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/entity/Ticket.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/repository/TicketRepository.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketTransferStreamConsumer.java
  module-ticket/src/test/java/com/example/moduleticket/ModuleTicketApplicationTests.java
Labels: ♻️Refactor

#30 ✨ Feat : Openfeign 서킷브레이커 적용
  module-ticket/build.gradle
  module-ticket/src/main/java/com/example/moduleticket/config/CircuitBreakerCustomConfig.java
  module-ticket/src/main/java/com/example/moduleticket/feign/FeignClientErrorDecoder.java
  module-ticket/src/main/java/com/example/moduleticket/global/argumentresolver/AuthUserArgumentResolver.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/ErrorCode.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/GlobalExceptionHandler.java
  module-ticket/src/main/java/com/example/moduleticket/global/exception/UnknownException.java
  module-ticket/src/main/java/com/example/moduleticket/util/SeatHoldRedisUtil.java
  module-ticket/src/main/resources/application.properties
Labels: ✨Feat 

#31 ♻️ Refactor : common 모듈 삭제 및 완전한 msa 분리 완료
  .github/workflows/ci.yml
  module-auction/build.gradle
  module-common/.gitattributes
  module-common/.gitignore
  module-common/build.gradle
  module-common/gradle/wrapper/gradle-wrapper.jar
  module-common/gradle/wrapper/gradle-wrapper.properties
  module-common/gradlew
  module-common/gradlew.bat
  module-common/src/main/java/com/example/modulecommon/ModuleCommonApplication.java
  module-common/src/main/java/com/example/modulecommon/exception/ErrorCode.java
  module-common/src/main/resources/application.properties
  module-common/src/test/java/com/example/modulecommon/ModuleCommonApplicationTests.java
  module-common/src/test/resources/application-test.properties
  module-game/build.gradle
  module-game/src/main/java/com/example/modulegame/common/image/ImageService.java
  module-game/src/main/java/com/example/modulegame/config/CachingConfig.java
  module-game/src/main/java/com/example/modulegame/config/RSocketClientConfig.java
  module-game/src/main/java/com/example/modulegame/domain/game/controller/GameController.java
  module-game/src/main/java/com/example/modulegame/domain/game/dto/SeatDto.java
  module-game/src/main/java/com/example/modulegame/domain/game/event/listener/RedisEventListener.java
  module-game/src/main/java/com/example/modulegame/domain/game/repository/GameRepository.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameCacheService.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameRSocketClientService.java
  module-game/src/main/java/com/example/modulegame/domain/game/service/GameService.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SeatController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/controller/SectionController.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/dto/SectionAndPositionDto.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/dto/request/SeatHoldRequest.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SeatRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SectionRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/StadiumRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatService.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatValidator.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SectionService.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/StadiumService.java
  module-game/src/main/java/com/example/modulegame/feign/client/TicketClient.java
  module-game/src/main/java/com/example/modulegame/global/annotation/LoginUser.java
  module-game/src/main/java/com/example/modulegame/global/argumentresolver/AuthUserArgumentResolver.java
  module-game/src/main/java/com/example/modulegame/global/entity/AuthUser.java
  module-game/src/main/java/com/example/modulegame/global/entity/Timestamped.java
  module-game/src/main/java/com/example/modulegame/global/exception/ErrorCode.java
  module-game/src/main/java/com/example/modulegame/global/exception/ErrorResponse.java
  module-game/src/main/java/com/example/modulegame/global/exception/GlobalExceptionHandler.java
  module-game/src/main/java/com/example/modulegame/global/exception/ServerException.java
  module-game/src/main/java/com/example/modulegame/global/util/PageUtil.java
  module-gateway/build.gradle
  module-gateway/src/main/java/com/example/modulegateway/config/GatewayUriMetricsConfiguration.java
  module-waiting/build.gradle
  module-waiting/src/main/java/com/example/modulewaiting/global/exception/ErrorCode.java
  module-waiting/src/main/java/com/example/modulewaiting/global/exception/ErrorResponse.java
  module-waiting/src/main/java/com/example/modulewaiting/global/exception/GlobalExceptionHandler.java
  module-waiting/src/main/java/com/example/modulewaiting/global/exception/ServerException.java
  module-waiting/src/main/java/com/example/modulewaiting/queue/service/QueueManager.java
  settings.gradle
Labels: ♻️Refactor

#32 ♻️ Refactor : feign client name 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionPaymentService.java
  module-auction/src/main/java/com/example/moduleauction/domain/auction/service/AuctionService.java
  module-auction/src/main/java/com/example/moduleauction/feign/GameClient.java
  module-auction/src/main/java/com/example/moduleauction/feign/PointClient.java
  module-auction/src/main/java/com/example/moduleauction/feign/SeatClient.java
  module-auction/src/main/java/com/example/moduleauction/feign/TicketClient.java
  module-auction/src/main/resources/application.properties
  module-auth/src/main/java/com/example/moduleauth/feign/PointService.java
  module-auth/src/main/resources/application.properties
  module-game/src/main/java/com/example/modulegame/domain/stadium/repository/SeatRepository.java
  module-game/src/main/java/com/example/modulegame/domain/stadium/service/SeatService.java
  module-game/src/main/java/com/example/modulegame/feign/client/AuctionClient.java
  module-game/src/main/java/com/example/modulegame/feign/client/ReservationClient.java
  module-game/src/main/java/com/example/modulegame/feign/client/TicketClient.java
  module-game/src/main/resources/application.properties
  module-gateway/src/main/resources/application.yml
  module-point/src/main/resources/application.properties
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationCreateService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/reservation/service/ReservationPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketPaymentService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketSeatService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketService.java
  module-ticket/src/main/java/com/example/moduleticket/domain/ticket/service/TicketTransferStreamConsumer.java
  module-ticket/src/main/java/com/example/moduleticket/feign/GameClient.java
  module-ticket/src/main/java/com/example/moduleticket/feign/PointClient.java
  module-ticket/src/main/java/com/example/moduleticket/feign/SeatClient.java
  module-ticket/src/main/resources/application.properties
  module-waiting/src/main/resources/application.properties
Labels: ♻️Refactor
